"""add review and audit tables

Revision ID: 60c266fb3553
Revises: 
Create Date: 2026-09-24 22:06:31.844477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60c266fb3553'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.String(length=100), nullable=False),
    sa.Column('parent_analysis_id', sa.String(length=100), nullable=True),
    sa.Column('audit_type', sa.String(length=50), nullable=False),
    sa.Column('compliance_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_controls', sa.Integer(), nullable=False),
    sa.Column('passed_controls', sa.Integer(), nullable=False),
    sa.Column('failed_controls', sa.Integer(), nullable=False),
    sa.Column('unknown_controls', sa.Integer(), nullable=False),
    sa.Column('approved_mapping_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_history_analysis_id'), 'audit_history', ['analysis_id'], unique=False)
    op.create_table('review_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.String(length=100), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('source_command', sa.Text(), nullable=False),
    sa.Column('ai_category', sa.String(length=100), nullable=True),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('normalized_field', sa.String(length=200), nullable=True),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_mappings_analysis_id'), 'review_mappings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_review_mappings_status'), 'review_mappings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_mappings_status'), table_name='review_mappings')
    op.drop_index(op.f('ix_review_mappings_analysis_id'), table_name='review_mappings')
    op.drop_table('review_mappings')
    op.drop_index(op.f('ix_audit_history_analysis_id'), table_name='audit_history')
    op.drop_table('audit_history')
    # ### end Alembic commands ###
