config system global
    set hostname FG-EDGE-02
    set admin-ssh enable
    set admin-telnet disable
end

config system admin
    set password-min-length 14
end

config log
    set status enable
end
