config system global
    set hostname FG-EDGE-01
    set admin-ssh disable
    set admin-telnet enable
    set some-future-feature enable
end

config system admin
    set password-min-length 8
end

config log
    set status disable
end
